### ISSUE TITLE
can't get Bitmap from reNX

### ISSUE THREAD

**Issue by KururuLABO** [angelsl/ms-reNX#6]
Hello i try to reNX to get Bitmap from nx file. But i can't get Bitmap from this method.

Bitmap m = NXCharacter.ResolvePath("/Accessory/01010000.img/info/iconRaw").ValueOrDie<Bitmap>();

![null](https://cloud.githubusercontent.com/assets/2968700/7526535/389ef4b4-f4c7-11e4-9254-d2f0bb51b615.png)

**Comment by retep998** [comment]
Are you sure the NX file has bitmaps?

**Comment by KururuLABO** [comment]
Yes, i'm sure because i convert from nx file by your program(WzToNX) and try to get bitmap from this file.

**Comment by retep998** [comment]
When converting a WZ file to an NX file make sure you passed the `--client` flag, otherwise the resulting NX file won't have any bitmaps or audio.

**Comment by angelsl** [comment]
So... what happens when you try to get the Bitmap? You set the breakpoint before the line executes. I can't tell anything from that screenshot.

**Comment by KururuLABO** [comment]
@retep998 Ok thx it's working fine.
@angelsl You can tell when breakpoint show Bitmap m = null;

**Comment by angelsl** [comment]
@KururuLABO If you set the breakpoint by clicking on the margin, the breakpoint occurs before the line executes.

So `Bitmap m` will obviously be `null`.
